# OpenAPI Specification: Robotics Textbook Platform

openapi: 3.0.0
info:
  title: Robotics Textbook Platform API
  description: API for the interactive Physical AI & Humanoid Robotics textbook
  version: 1.0.0
  contact:
    name: Textbook Development Team
    email: textbook@example.com

servers:
  - url: https://api.robotics-textbook.com/v1
    description: Production server
  - url: https://staging-api.robotics-textbook.com/v1
    description: Staging server

paths:
  /students:
    post:
      summary: Register a new student
      description: Creates a new student account in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentRegistration'
      responses:
        '201':
          description: Student successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input
        '409':
          description: Student with this email already exists

    get:
      summary: Get all students (admin only)
      description: Retrieves a list of all students (admin access required)
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '401':
          description: Unauthorized access
        '403':
          description: Forbidden (not admin)

  /students/{studentId}:
    get:
      summary: Get student profile
      description: Retrieves a specific student's profile information
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Student profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found

    put:
      summary: Update student profile
      description: Updates a student's profile information
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentUpdate'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input
        '404':
          description: Student not found

  /modules:
    get:
      summary: Get all available modules
      description: Retrieves a list of all available textbook modules
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'

  /modules/{moduleId}:
    get:
      summary: Get module details
      description: Retrieves details for a specific module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Module details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Module not found

  /modules/{moduleId}/progress:
    get:
      summary: Get student progress in module
      description: Retrieves a student's progress in a specific module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
        - name: studentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Student progress in module
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModuleProgress'
        '404':
          description: Module or student not found

    post:
      summary: Update student progress in module
      description: Updates a student's progress in a specific module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModuleProgressUpdate'
      responses:
        '200':
          description: Progress updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModuleProgress'
        '400':
          description: Invalid input
        '404':
          description: Module or student not found

  /certificates:
    get:
      summary: Get all certificates
      description: Retrieves all certificates for a student
      parameters:
        - name: studentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of certificates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Certificate'

  /certificates/{certificateId}:
    get:
      summary: Get certificate details
      description: Retrieves details for a specific certificate
      parameters:
        - name: certificateId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Certificate details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Certificate'
        '404':
          description: Certificate not found

components:
  schemas:
    Student:
      type: object
      required:
        - studentId
        - email
        - name
        - enrollmentDate
      properties:
        studentId:
          type: string
          description: Unique identifier for the student
        email:
          type: string
          format: email
          description: Student's email address
        name:
          type: string
          description: Student's display name
          minLength: 1
          maxLength: 100
        enrollmentDate:
          type: string
          format: date-time
          description: When the student enrolled
        progress:
          type: object
          description: Map of module progress
          additionalProperties:
            $ref: '#/components/schemas/ModuleProgress'
        completedCertificates:
          type: array
          items:
            $ref: '#/components/schemas/Certificate'
        preferences:
          $ref: '#/components/schemas/UserPreferences'

    StudentRegistration:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          minLength: 1
          maxLength: 100
        password:
          type: string
          minLength: 8
          description: Password must be at least 8 characters

    StudentUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        preferences:
          $ref: '#/components/schemas/UserPreferences'

    Module:
      type: object
      required:
        - moduleId
        - title
        - description
      properties:
        moduleId:
          type: string
          description: Unique identifier for the module
        title:
          type: string
          description: Display title of the module
        description:
          type: string
          description: Brief description of the module
        duration:
          type: string
          description: Estimated completion time
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/Chapter'
        learningObjectives:
          type: array
          items:
            type: string
        prerequisites:
          type: array
          items:
            type: string

    Chapter:
      type: object
      required:
        - chapterId
        - title
        - content
      properties:
        chapterId:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Chapter title
        content:
          type: string
          description: Chapter content in Markdown format
        codeExamples:
          type: array
          items:
            $ref: '#/components/schemas/CodeExample'
        learningOutcomes:
          type: array
          items:
            type: string

    CodeExample:
      type: object
      required:
        - exampleId
        - title
        - code
        - language
      properties:
        exampleId:
          type: string
          description: Unique identifier for the code example
        title:
          type: string
          description: Description of the example
        code:
          type: string
          description: The actual code content
        language:
          type: string
          description: Programming language identifier
        environment:
          type: string
          description: Execution environment type
        expectedOutput:
          type: string
          description: What the example should produce
        instructions:
          type: string
          description: How to use/run the example

    ModuleProgress:
      type: object
      required:
        - studentId
        - moduleId
        - overallCompletion
      properties:
        studentId:
          type: string
          description: Reference to student
        moduleId:
          type: string
          description: Reference to module
        chapterProgress:
          type: object
          description: Completion status of each chapter
          additionalProperties:
            type: boolean
        overallCompletion:
          type: number
          description: Percentage complete (0-100)
          minimum: 0
          maximum: 100
        lastAccessed:
          type: string
          format: date-time
          description: When student last accessed
        timeSpent:
          type: integer
          description: Time spent in seconds

    ModuleProgressUpdate:
      type: object
      properties:
        chapterId:
          type: string
          description: ID of chapter being updated
        completed:
          type: boolean
          description: Whether the chapter is completed
        timeSpent:
          type: integer
          description: Additional time spent in seconds

    Certificate:
      type: object
      required:
        - certificateId
        - studentId
        - moduleId
        - issueDate
        - title
      properties:
        certificateId:
          type: string
          description: Unique identifier for the certificate
        studentId:
          type: string
          description: Recipient of the certificate
        moduleId:
          type: string
          description: Module completed
        issueDate:
          type: string
          format: date-time
          description: When issued
        title:
          type: string
          description: Certificate title
        content:
          type: string
          description: Description of achievement

    UserPreferences:
      type: object
      properties:
        darkMode:
          type: boolean
          description: Whether to use dark theme
        fontSize:
          type: string
          enum: [small, medium, large]
          description: Text size preference
        highContrast:
          type: boolean
          description: Accessibility setting
        language:
          type: string
          description: Preferred language
        codeTheme:
          type: string
          description: Code block syntax highlighting theme